services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
      - ADDRESS=0.0.0.0
      - DB_ADDRESS=$REDIS_SERVICE_NAME
      - DB_PORT=$DB_RUN_PORT
  redis:
    image: redis:alpine
    hostname: $REDIS_SERVICE_NAME
    ports:
      - $DB_RUN_PORT:$DB_RUN_PORT
