services:
  app:
    build: .
    
    depends_on:
      - redis
    environment:
      - PORT=$HTTP_PORT
      - ADDRESS=0.0.0.0
      - DB_ADDRESS=$REDIS_SERVICE_NAME
      - DB_PORT=6379
    ports:
      - "$HTTP_PORT:$HTTP_PORT"
  redis:
    image: redis:alpine
    hostname: $REDIS_SERVICE_NAME
    ports:
      - "6379:6379"
