package config

const (
	ENV_SERVER_PORT = "PORT"
	ENV_SERVER_IP   = "ADDRESS"
	ENV_DB_IP       = "DB_ADDRESS"
	ENV_DB_PORT     = "DB_PORT"
	ENV_DB_USER     = "DB_USER"
	ENV_DB_NAME     = "DB_NAME"
	ENV_DB_PWD      = "DB_PWD"

	ENV_DB_SSL_MODE         = "DB_SSL_MODE"
	DEFAULT_VAL_SERVER_PORT = "8080"
	DEFAULT_VAL_SERVER_IP   = "127.0.0.1"
	DEFAULT_VAL_DB_IP       = "0.0.0.0"
	DEFAULT_VAL_DB_PORT     = "5432"
	DEFAULT_VAL_DB_USER     = "postgres"
	DEFAULT_VAL_DB_NAME     = "urls"
	DEFAULT_VAL_DB_PWD      = "password"
	DEFAULT_VAL_DB_SSL_MODE = "disable"
)
